### ISSUE TITLE
No way to retrieve assessment uuid from guanine UI

### ISSUE THREAD

**Issue by hexylena** [TAMU-CPT/guanine#7]

**Comment by elenimijalis** [comment]
can you elaborate? Why is it necessary to retrieve it from the UI?

**Comment by hexylena** [comment]
For the programmer adding building the tool, it would be nicer to just
click on an assessment and get an ID, instead of having to use the API
output or the admin interface. Programmers building tools related to
guanine will be closesly associated with the course and thus using the main
guanine site as well.

Den tir. 1. nov. 2016, 16.49 skrev Eleni Mijalis notifications@github.com:

**Comment by elenimijalis** [comment]
possible "copy to clipboard" mechanism

**Comment by hexylena** [comment]
Dupe of https://github.com/TAMU-CPT/guanine-frontend/issues/5
